remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Cap Recognizer
description: An image classification API that classifies 18 different types of traffic_sign.

author:
  name: Mohammad Abdur Sobhan Riad