remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll@master

plugins:
- jekyll-remote-theme

title: Traffic_Sign_Detector
description: An image classification API that classifies 18 different types of traffic_sign.

author:
  name: Mohammad Abdur Sobhan Riad
  
round-avatar: true
post_search: true

navbar-links:
   Traffic_Sign_Recognizer : "docs/traffic_sign_recognizer.html"
