remote_theme: daviddarnes/alembic@master

plugins:
- jekyll-remote-theme

title: Traffic_Sign_Detector
description: An image classification API that classifies 18 different types of traffic_sign.

author:
  name: Mohammad Abdur Sobhan Riad

# navbar-links:
#   Recognizer: "docs/traffic_sign_recognizer.html"
  
